# Generated by Django 5.0.2 on 2024-03-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checked_campus_facilities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='checked_ham_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='known_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='picked_classes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='picked_dorm_room',
            field=models.BooleanField(default=False),
        ),
    ]
