# Generated by Django 5.0.2 on 2024-02-19 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
                ('group_description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='collegeclass',
            name='calendar_event',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='collegeClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.collegeclass'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collegeclass',
            name='class_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.group'),
        ),
    ]
