# Generated by Django 5.0.2 on 2024-02-19 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_group_remove_collegeclass_calendar_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='collegeClass',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='group',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.group'),
        ),
        migrations.DeleteModel(
            name='CollegeClass',
        ),
    ]
