# Generated by Django 5.0.2 on 2024-02-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_remove_calendarevent_collegeclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
