# Generated by Django 5.0.2 on 2024-02-21 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_rename_group_calendargroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
