<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-02-21 03:57
=======
# Generated by Django 5.0.2 on 2024-02-20 16:26
>>>>>>> b3b00023041fa87fa4b225b214073d7222be85c1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteText', models.TextField()),
=======
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("noteText", models.TextField()),
>>>>>>> b3b00023041fa87fa4b225b214073d7222be85c1
            ],
        ),
    ]
