# Generated by Django 5.0.2 on 2024-02-19 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSpent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timerName', models.CharField(max_length=64)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('currentlyRunning', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=64)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timerApp.timespent')),
            ],
        ),
    ]
