# Generated by Django 5.0.2 on 2024-03-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dorms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormtype', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=200)),
                ('dormpic1', models.ImageField(upload_to='')),
                ('dormpic2', models.ImageField(upload_to='')),
                ('dormpic3', models.ImageField(upload_to='')),
                ('foodoptions', models.CharField(max_length=200)),
                ('is_current_dorm', models.BooleanField(default=False)),
            ],
        ),
    ]
