# Generated by Django 5.0.2 on 2024-03-13 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0005_calendarevent_author_delete_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dorms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormtype', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('dormpic1', models.ImageField(blank=True, default='default.webp', upload_to='dormview')),
                ('dormpic2', models.ImageField(blank=True, default='default.webp', upload_to='dormview')),
                ('dormpic3', models.ImageField(blank=True, default='default.webp', upload_to='dormview')),
                ('foodoptions', models.CharField(blank=True, max_length=200)),
                ('is_current_dorm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotebank', models.JSONField()),
                ('last_displayed_quote', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
