# Generated by Django 5.0.3 on 2024-03-13 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0006_dorms_quotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='author',
        ),
        migrations.CreateModel(
            name='UserChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_ncf_email', models.BooleanField(default=False)),
                ('subscribe_to_ncfsafe', models.BooleanField(default=False)),
                ('fafsa', models.BooleanField(default=False)),
                ('residency_classification', models.BooleanField(default=False)),
                ('housing_and_meal_plans', models.BooleanField(default=False)),
                ('student_id', models.BooleanField(default=False)),
                ('parking_pass', models.BooleanField(default=False)),
                ('download_corq', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
