# Generated by Django 5.0.2 on 2024-03-15 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0008_calendarevent_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="userchecklist",
            old_name="access_ncf_email",
            new_name="bath_towel",
        ),
        migrations.RenameField(
            model_name="userchecklist",
            old_name="download_corq",
            new_name="bathrobe",
        ),
        migrations.RenameField(
            model_name="userchecklist",
            old_name="fafsa",
            new_name="bedding",
        ),
        migrations.RenameField(
            model_name="userchecklist",
            old_name="housing_and_meal_plans",
            new_name="cleaning_supplies",
        ),
        migrations.RenameField(
            model_name="userchecklist",
            old_name="parking_pass",
            new_name="clothes_hangers",
        ),
        migrations.RenameField(
            model_name="userchecklist",
            old_name="residency_classification",
            new_name="clothing",
        ),
        migrations.RenameField(
            model_name="userchecklist",
            old_name="student_id",
            new_name="get_keys_from_housing",
        ),
        migrations.RenameField(
            model_name="userchecklist",
            old_name="subscribe_to_ncfsafe",
            new_name="housing_registration",
        ),
        migrations.AddField(
            model_name="quotes",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userchecklist",
            name="key_chain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userchecklist",
            name="lamps",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userchecklist",
            name="laundry_supplies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userchecklist",
            name="room_deodorizing_spray",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userchecklist",
            name="school_supplies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userchecklist",
            name="toiletries",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userchecklist",
            name="wastebasket_and_trash_bag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userchecklist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
