# Generated by Django 5.0.2 on 2024-02-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoListApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
